ALTER TABLE table CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE deliverystops CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE email CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE estimatedtimes CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE locations CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE truckroute CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE trucks CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;